# Generated by Django 3.2.5 on 2021-07-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('time', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary/')),
                ('weather', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
